# Generated by Django 5.1.1 on 2024-09-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0004_alter_playbook_object_wiki_page_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Archived_Playbook',
        ),
        migrations.DeleteModel(
            name='Archived_Playbook_Object',
        ),
        migrations.DeleteModel(
            name='Archived_Semantic_Relation',
        ),
    ]
