# Generated by Django 4.1 on 2024-08-13 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], default='str', max_length=200)),
                ('profile', models.CharField(default='default', max_length=200)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Archived_Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('wiki_page_name', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('wiki_form', models.CharField(blank=True, max_length=200, null=True)),
                ('archived_on', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-archived_on'],
            },
        ),
        migrations.CreateModel(
            name='Archived_Playbook_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('wiki_page_name', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('wiki_form', models.CharField(blank=True, max_length=200, null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_objects', to='sasp.archived_playbook')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fields', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('wiki_page_name', models.CharField(editable=False, max_length=200, unique=True)),
                ('wiki_form', models.CharField(editable=False, max_length=200)),
                ('permission_view', models.JSONField(default=dict)),
                ('permission_edit', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playbook_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('wiki_page_name', models.CharField(max_length=200, unique=True)),
                ('content', models.JSONField(default=dict)),
                ('wiki_form', models.CharField(blank=True, max_length=200, null=True)),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbook_objects', to='sasp.playbook')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CACAO_1_1_PlaybookObject',
            fields=[
                ('playbook_object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sasp.playbook_object')),
            ],
            bases=('sasp.playbook_object',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sso_token', models.JSONField(blank=True, null=True)),
                ('sso_token_expires', models.DateTimeField(blank=True, null=True)),
                ('sso_user_info', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semantic_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=200)),
                ('object_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_sources', to='sasp.playbook_object')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_relations', to='sasp.playbook')),
                ('subject_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_relations', to='sasp.playbook_object')),
            ],
            options={
                'ordering': ['subject_field', 'predicate', 'object_field'],
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('cert', models.JSONField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('additional_fields', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='sasp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Automation_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=200, null=True)),
                ('case_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('confirmation_requests', models.JSONField(blank=True, default=dict)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_instances', to='sasp.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='Archived_Semantic_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_atomic', models.CharField(blank=True, max_length=200, null=True)),
                ('predicate', models.CharField(max_length=200)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relations', to='sasp.archived_playbook_object')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_relations', to='sasp.archived_playbook')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='sasp.archived_playbook_object')),
            ],
            options={
                'ordering': ['subject', 'predicate', 'object'],
            },
        ),
        migrations.CreateModel(
            name='CACAO_1_1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.playbook',),
        ),
        migrations.CreateModel(
            name='SAPPAN',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.playbook',),
        ),
        migrations.AddIndex(
            model_name='semantic_relation',
            index=models.Index(fields=['playbook'], name='sasp_semant_playboo_5debad_idx'),
        ),
        migrations.AddIndex(
            model_name='archived_semantic_relation',
            index=models.Index(fields=['playbook'], name='sasp_archiv_playboo_2034a7_idx'),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_CivicLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Command',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_ContactInformation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_DataMarking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Extension',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_ExternalReference',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_GpsLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Playbook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Signature',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Step_Object',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Target',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_Variable',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_playbookobject',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_AttackAgentTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_AttackerTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_AttackGroupTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_EndStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_GeneralNetworkAddressTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_GroupTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_HttpApiTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_IepMarking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_datamarking',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_IfConditionStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_IndividualTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_KaliLinuxTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_LocationTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_OrganizationTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_ParallelStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_PlaybookStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_SectorTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_SecurityInfrastructureCategoryTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_SingleActionStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_SshCliTarget',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_target',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_StartStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_StatementMarking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_datamarking',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_SwitchConditionStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_TlpMarking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_datamarking',),
        ),
        migrations.CreateModel(
            name='CACAO_1_1_WhileConditionStep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sasp.cacao_1_1_step_object',),
        ),
    ]
