# Generated by Django 4.1 on 2024-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playbook_object',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
