# Generated by Django 5.1.1 on 2024-09-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0003_remove_playbook_archived_playbook_archive_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook_object',
            name='wiki_page_name',
            field=models.CharField(max_length=200),
        ),
    ]
