# Generated by Django 5.1.1 on 2024-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0005_remove_archived_playbook_object_playbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sso_user_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
