# Generated by Django 5.1.5 on 2025-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0007_remove_automation_instance_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation_instance',
            name='objects_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automation_instance',
            name='playbook_frozen',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
