# Generated by Django 5.1.5 on 2025-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasp', '0008_automation_instance_objects_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
